# Generated by Django 3.2.15 on 2022-09-21 02:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sgresume.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_Name', models.TextField(max_length=500)),
                ('start_year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), sgresume.models.max_value_current_year])),
                ('end_year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), sgresume.models.max_value_current_year])),
                ('percentage', models.CharField(max_length=500)),
                ('class_studied', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.TextField(max_length=500)),
                ('project_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.TextField(max_length=500)),
                ('project_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(max_length=500)),
                ('job_description', models.TextField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Description', models.TextField()),
                ('Academics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgresume.academics')),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgresume.project')),
                ('Skills', models.ManyToManyField(to='sgresume.Skills')),
                ('WorkExperiance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgresume.workexperiance')),
            ],
        ),
    ]
