# Generated by Django 3.2.15 on 2022-09-21 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='project_title',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
