# Generated by Django 3.2.15 on 2022-09-21 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0002_auto_20220921_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='Academics',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='WorkExperiance',
        ),
        migrations.AddField(
            model_name='academics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgresume.geeksmodel'),
        ),
    ]
