# Generated by Django 3.2.15 on 2022-09-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0003_auto_20220921_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgresume.geeksmodel'),
        ),
        migrations.AddField(
            model_name='workexperiance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgresume.geeksmodel'),
        ),
    ]
