# Generated by Django 3.2.15 on 2022-09-21 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0004_auto_20220921_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='board',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academics',
            name='institute_Name',
            field=models.TextField(max_length=1000),
        ),
    ]
