# Generated by Django 3.2.15 on 2022-09-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0005_auto_20220921_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='institute_Name',
            field=models.CharField(max_length=1000),
        ),
    ]
