# Generated by Django 3.2.15 on 2022-09-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0006_alter_academics_institute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperiance',
            name='company',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workexperiance',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
