# Generated by Django 3.2.15 on 2022-09-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0007_auto_20220921_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
