# Generated by Django 3.2.15 on 2022-09-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0008_project_repo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='gmail',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='linked_in',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='phone_no',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
