# Generated by Django 3.2.15 on 2022-09-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0009_auto_20220921_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geeksmodel',
            old_name='gmail',
            new_name='github',
        ),
    ]
