# Generated by Django 3.2.15 on 2022-09-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0010_rename_gmail_geeksmodel_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=50)),
            ],
        ),
    ]
