# Generated by Django 3.2.15 on 2022-09-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0011_tools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geeksmodel',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='geeksmodel',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='Skills',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='skills',
            field=models.ManyToManyField(to='sgresume.Skills'),
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='tools',
            field=models.ManyToManyField(to='sgresume.Tools'),
        ),
    ]
