# Generated by Django 3.2.15 on 2022-09-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0013_auto_20220922_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperiance',
            name='designation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
