# Generated by Django 3.2.15 on 2022-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0014_workexperiance_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='resume'),
        ),
    ]
