# Generated by Django 3.2.15 on 2022-09-22 17:22

from django.db import migrations, models
import sgresume.models


class Migration(migrations.Migration):

    dependencies = [
        ('sgresume', '0015_geeksmodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=sgresume.models.profile_picture_upload_path),
        ),
    ]
